name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - master  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify Python version as needed

    - name: Build current documentation
      run: |
        git fetch --tags
        latest_tag=$(git tag --sort=-v:refname | head -n 1)
        echo "Latest tag: $latest_tag"
        git checkout "$latest_tag"
        pip install -e .
        pip install -e ".[doc]"
        
        cd docs

        # Replace %VERSION% with the latest tag in conf.py
        sed -i "s/%VERSION%/$latest_tag/g" conf.py

        make html
        mkdir -p "../build/html/$latest_tag"
        cp -r build/html/* "../build/html/$latest_tag/"
        rm -rf build/html
        git stash

    - name: Install dependencies
      run: |
        git checkout master  
        python -m pip install --upgrade pip
        pip install -e .
        pip install -e .[doc]

    - name: Build current documentation
      run: |
        cd docs
        make html
        cp -r build/html/* ../build/html/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html/  # Adjusted path since we're copying docs to root build directory
